/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.beans.PropertyChangeEvent;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;
import javax.swing.JTabbedPane;
import javax.swing.SwingUtilities;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.Document;
import javax.swing.text.JTextComponent;
import voter.Voter;

/**
 *
 * @author Hinnata
 */
public class ClientFrame extends javax.swing.JFrame {
    
         private Voter myvoter;
         int[] physicalSamplesArray;
         int[] dropSamplesArray;
	/**
	 * Creates new form ClientFrame
	 */
	public ClientFrame() {
		initComponents();
                myInitComponents();
	}
        
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField8 = new javax.swing.JTextField();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelBackground = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextWeightBackground = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaResultBackground = new javax.swing.JTextArea();
        jButtonBackground = new javax.swing.JButton();
        jButtonDetailsBackground = new javax.swing.JButton();
        jPanelPersonal = new javax.swing.JPanel();
        jTextDropSamples = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextCarbosInMealPersonal = new javax.swing.JTextField();
        jTextTodayPhysicalActivity = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldCarbosProcessedPersonal = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextBloodSugarPersonal = new javax.swing.JTextField();
        jTextTargetBloodSugarPersonal = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextPhysicalSamples = new javax.swing.JTextField();
        jButtonPersonal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaResultPersonal = new javax.swing.JTextArea();
        jLabel33 = new javax.swing.JLabel();
        jButtonDetailsPersonal = new javax.swing.JButton();
        jPanelStandard = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextIndividualSensitivityStandard = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextCarbosInMealStandard = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonStandard = new javax.swing.JButton();
        jTextFieldCarbosProcessedStandard = new javax.swing.JTextField();
        jTextBloodSugarStandard = new javax.swing.JTextField();
        jTextTargetBloodSugarStandard = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaResultStandard = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jButtonDetailsStandard = new javax.swing.JButton();

        jTextField8.setText("jTextField8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel14.setText("kg      (between 40 and 130)");

        jLabel13.setText("Weight:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Background Insulin");

        jTextAreaResultBackground.setEditable(false);
        jTextAreaResultBackground.setColumns(20);
        jTextAreaResultBackground.setRows(5);
        jScrollPane3.setViewportView(jTextAreaResultBackground);

        jButtonBackground.setText("Calculate Insulin Dose");
        jButtonBackground.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackgroundActionPerformed(evt);
            }
        });

        jButtonDetailsBackground.setText("Details");
        jButtonDetailsBackground.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetailsBackgroundActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBackgroundLayout = new javax.swing.GroupLayout(jPanelBackground);
        jPanelBackground.setLayout(jPanelBackgroundLayout);
        jPanelBackgroundLayout.setHorizontalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addComponent(jButtonBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDetailsBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextWeightBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelBackgroundLayout.setVerticalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextWeightBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jButtonBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDetailsBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane.addTab("Background Dose", jPanelBackground);

        jLabel26.setText("Samples of physical activity level in a given past day (separated by space(e.g. 5 6 7)):");

        jLabel27.setText("Samples of drops in blood sugar from one unit of insulin in that past day (separated by space(e.g. 5 6 7))");

        jLabel22.setText("Today’s physical activity level:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Personal Sensitivity Meal Time Insuline Dose");

        jLabel16.setText("Carbohydrates in the meal:");

        jLabel25.setText("scale (0 - no activity to 10 - very high activity)");

        jLabel28.setText("scale (0 - no activity to 10 - very high activity)");

        jLabel29.setText("mg/dl  (between 15 and 100)");

        jLabel17.setText("g      (between 60 and 120)");

        jLabel18.setText("Carbohydrates processed by 1 unit of rapid acting insulin:");

        jTextFieldCarbosProcessedPersonal.setText("12");

        jLabel19.setText("g/unit      (between 10 and 15)");

        jLabel20.setText("Actual blood sugar level measured before the meal:");

        jLabel21.setText("Target blood sugar before the meal:");

        jLabel23.setText("mg/dl      (between 120 and 250)");

        jLabel24.setText("mg/dl      (between 80 and 120)");

        jButtonPersonal.setText("Calculate Insulin Dose");
        jButtonPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPersonalActionPerformed(evt);
            }
        });

        jTextAreaResultPersonal.setEditable(false);
        jTextAreaResultPersonal.setColumns(20);
        jTextAreaResultPersonal.setRows(5);
        jScrollPane1.setViewportView(jTextAreaResultPersonal);

        jLabel33.setText("Note: Number of samples of physical activity has to be the same as the number of drops in blood sugar");

        jButtonDetailsPersonal.setText("Details");
        jButtonDetailsPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetailsPersonalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPersonalLayout = new javax.swing.GroupLayout(jPanelPersonal);
        jPanelPersonal.setLayout(jPanelPersonalLayout);
        jPanelPersonalLayout.setHorizontalGroup(
            jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPersonalLayout.createSequentialGroup()
                        .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addGroup(jPanelPersonalLayout.createSequentialGroup()
                                .addComponent(jTextDropSamples, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel29))
                            .addComponent(jLabel27)
                            .addGroup(jPanelPersonalLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextTodayPhysicalActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25))
                            .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelPersonalLayout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextCarbosInMealPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel15))
                            .addGroup(jPanelPersonalLayout.createSequentialGroup()
                                .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelPersonalLayout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextBloodSugarPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addGroup(jPanelPersonalLayout.createSequentialGroup()
                                        .addComponent(jTextFieldCarbosProcessedPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19))))
                            .addGroup(jPanelPersonalLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextTargetBloodSugarPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24)))
                        .addGap(196, 230, Short.MAX_VALUE))
                    .addGroup(jPanelPersonalLayout.createSequentialGroup()
                        .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPersonalLayout.createSequentialGroup()
                                .addComponent(jTextPhysicalSamples, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel28))
                            .addComponent(jLabel33))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelPersonalLayout.createSequentialGroup()
                        .addComponent(jButtonPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDetailsPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanelPersonalLayout.setVerticalGroup(
            jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextCarbosInMealPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldCarbosProcessedPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextBloodSugarPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23))
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextTargetBloodSugarPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24))
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextTodayPhysicalActivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPhysicalSamples, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(11, 11, 11)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDropSamples, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGap(18, 18, 18)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jButtonDetailsPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane.addTab("Personal Sensitivity Dose", jPanelPersonal);

        jLabel6.setText("Actual blood sugar level measured before the meal:");

        jLabel8.setText("Target blood sugar before the meal:");

        jLabel10.setText("Individual sensitivity:");

        jTextIndividualSensitivityStandard.setText("50");

        jLabel11.setText("mg/dl      (between 15 and 100)");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Standard Meal Time Insulin Dose");

        jLabel2.setText("Carbohydratesin the meal:");

        jLabel3.setText("g      (between 60 and 120)");

        jLabel4.setText("Carbohydrates processed by 1 unit of rapid acting insulin:");

        jButtonStandard.setText("Calculate Insulin Dose");
        jButtonStandard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStandardActionPerformed(evt);
            }
        });

        jTextFieldCarbosProcessedStandard.setText("12");

        jTextAreaResultStandard.setEditable(false);
        jTextAreaResultStandard.setColumns(20);
        jTextAreaResultStandard.setRows(5);
        jScrollPane5.setViewportView(jTextAreaResultStandard);

        jLabel30.setText("mg/dl      (between 120 and 250)");

        jLabel31.setText("mg/dl      (between 80 and 120)");

        jLabel32.setText("g/unit      (between 10 and 15)");

        jButtonDetailsStandard.setText("Details");
        jButtonDetailsStandard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetailsStandardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelStandardLayout = new javax.swing.GroupLayout(jPanelStandard);
        jPanelStandard.setLayout(jPanelStandardLayout);
        jPanelStandardLayout.setHorizontalGroup(
            jPanelStandardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStandardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelStandardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelStandardLayout.createSequentialGroup()
                        .addComponent(jButtonStandard, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDetailsStandard, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5))
                    .addGroup(jPanelStandardLayout.createSequentialGroup()
                        .addGroup(jPanelStandardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanelStandardLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextCarbosInMealStandard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(jPanelStandardLayout.createSequentialGroup()
                                .addGroup(jPanelStandardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelStandardLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextTargetBloodSugarStandard))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelStandardLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextIndividualSensitivityStandard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel31))
                            .addGroup(jPanelStandardLayout.createSequentialGroup()
                                .addGroup(jPanelStandardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelStandardLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldCarbosProcessedStandard))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelStandardLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextBloodSugarStandard, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel30)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel32)))
                        .addGap(0, 131, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelStandardLayout.setVerticalGroup(
            jPanelStandardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStandardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanelStandardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelStandardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextCarbosInMealStandard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelStandardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldCarbosProcessedStandard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelStandardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextBloodSugarStandard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(7, 7, 7)
                .addGroup(jPanelStandardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextTargetBloodSugarStandard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelStandardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelStandardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextIndividualSensitivityStandard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addGroup(jPanelStandardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5)
                    .addComponent(jButtonStandard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDetailsStandard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane.addTab("Standard Meal Time Dose", jPanelStandard);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void myInitComponents(){
        
         myvoter = new Voter();
         
        //Listener para mudança de tabs
        ChangeListener changeListener = new ChangeListener() {
            
            public void stateChanged(ChangeEvent changeEvent) {
              JTabbedPane sourceTabbedPane = (JTabbedPane) changeEvent.getSource();
              //int index = sourceTabbedPane.getSelectedIndex();
              //System.out.println("Tab changed to: " + sourceTabbedPane.getTitleAt(index));
              
              //Standard
              jTextCarbosInMealStandard.setText("");
              jTextFieldCarbosProcessedStandard.setText("12");
              jTextBloodSugarStandard.setText("");
              jTextTargetBloodSugarStandard.setText("");
              jTextIndividualSensitivityStandard.setText("50");
              jTextAreaResultStandard.setText("");
              //Personal
              jTextCarbosInMealPersonal.setText("");
              jTextFieldCarbosProcessedPersonal.setText("12");
              jTextBloodSugarPersonal.setText("");
              jTextTargetBloodSugarPersonal.setText("");
              jTextTodayPhysicalActivity.setText("");
              jTextPhysicalSamples.setText("");
              jTextDropSamples.setText("");
              jTextAreaResultPersonal.setText("");
              //Background
              jTextWeightBackground.setText("");
              jTextAreaResultBackground.setText("");
              
              jButtonDetailsBackground.setEnabled(false);
              jButtonDetailsPersonal.setEnabled(false);
              jButtonDetailsStandard.setEnabled(false);
              
            }
        };
        jTabbedPane.addChangeListener(changeListener);
        
        //Listeners para alterações aos text fields (para desbloquear o butão)
        
        //Standard
        ChangeListener standardValueListener = new ChangeListener() {
            public void stateChanged(ChangeEvent changeEvent) {
              String carboMeal = jTextCarbosInMealStandard.getText();
              String carboProcessed = jTextFieldCarbosProcessedStandard.getText();
              String bloodSugar = jTextBloodSugarStandard.getText();
              String targetBloodSugar = jTextTargetBloodSugarStandard.getText();
              String sensitivity = jTextIndividualSensitivityStandard.getText();
              
              jButtonDetailsBackground.setEnabled(false);
              jButtonDetailsPersonal.setEnabled(false);
              jButtonDetailsStandard.setEnabled(false);
        
              if(carboMeal.isEmpty() || carboProcessed.isEmpty() || bloodSugar.isEmpty() || targetBloodSugar.isEmpty() || sensitivity.isEmpty()){
                  jButtonStandard.setEnabled(false);
              }else if(isNumeric(carboMeal) && isNumeric(carboProcessed) && isNumeric(bloodSugar) && isNumeric(targetBloodSugar) && isNumeric(sensitivity)){
                  int cb = Integer.parseInt(carboMeal);
                  int cp = Integer.parseInt(carboProcessed);
                  int bs = Integer.parseInt(bloodSugar);
                  int tbs = Integer.parseInt(targetBloodSugar);
                  int s = Integer.parseInt(sensitivity);
                  if(cb<60 || cb>120){
                    jButtonStandard.setEnabled(false);
                  }else  if(cp<10 || cp>15){
                    jButtonStandard.setEnabled(false);
                  }else  if(bs>250 || bs<120){
                    jButtonStandard.setEnabled(false);
                  }else  if(tbs>120 || tbs<80){
                    jButtonStandard.setEnabled(false);
                  }else  if(s>100 || s<15){
                    jButtonStandard.setEnabled(false);
                  }else jButtonStandard.setEnabled(true);
              }
            }
        };
        
        addChangeListener(jTextCarbosInMealStandard, standardValueListener);
        addChangeListener(jTextFieldCarbosProcessedStandard,standardValueListener);
        addChangeListener(jTextBloodSugarStandard,standardValueListener);
        addChangeListener(jTextTargetBloodSugarStandard,standardValueListener);
        addChangeListener(jTextIndividualSensitivityStandard,standardValueListener);
          
        //Personal
        ChangeListener personalValueListener = new ChangeListener() {
            public void stateChanged(ChangeEvent changeEvent) {
              String carboMeal = jTextCarbosInMealPersonal.getText();
              String carboProcessed = jTextFieldCarbosProcessedPersonal.getText();
              String bloodSugar = jTextBloodSugarPersonal.getText();
              String targetBloodSugar = jTextTargetBloodSugarPersonal.getText();
              String physical = jTextTodayPhysicalActivity.getText();
              String physicalSamples = jTextPhysicalSamples.getText();
              String dropSamples = jTextDropSamples.getText();
              
              List<String> physicalSamplesList = Arrays.asList(physicalSamples.split("\\s+"));
              List<String> dropSamplesList = Arrays.asList(dropSamples.split("\\s+"));
              
                            
              jButtonDetailsBackground.setEnabled(false);
              jButtonDetailsPersonal.setEnabled(false);
              jButtonDetailsStandard.setEnabled(false);
              
              if(physicalSamplesList.size()>=2 && physicalSamplesList.size()<=10 && dropSamplesList.size()>=2 && dropSamplesList.size()<=10 && dropSamplesList.size()==physicalSamplesList.size()){
                  physicalSamplesArray = new int[physicalSamplesList.size()];
                  dropSamplesArray = new int[dropSamplesList.size()];
                  
                  for(int i=0;i<physicalSamplesList.size();i++){
                      if(isNumeric(physicalSamplesList.get(i)) && isNumeric(dropSamplesList.get(i)) ){
                          int pv = Integer.parseInt(physicalSamplesList.get(i));
                          int dv = Integer.parseInt(dropSamplesList.get(i));
                          if(pv<=10 && pv>=0 && dv>=15 && dv<=100){
                            physicalSamplesArray[i]=pv;
                            dropSamplesArray[i]=dv;
                          }else{
                              jButtonPersonal.setEnabled(false);
                              return;
                          }
                      }else{
                           jButtonPersonal.setEnabled(false);
                          return;
                      }
                  }
              }else{
                  jButtonPersonal.setEnabled(false);
                  return;
              }
              
              if(carboMeal.isEmpty() || carboProcessed.isEmpty() || bloodSugar.isEmpty() || targetBloodSugar.isEmpty() || physical.isEmpty()){
                  jButtonPersonal.setEnabled(false);
              }else if(isNumeric(carboMeal) && isNumeric(carboProcessed) && isNumeric(bloodSugar) && isNumeric(targetBloodSugar) && isNumeric(physical)){
                  int cb = Integer.parseInt(carboMeal);
                  int cp = Integer.parseInt(carboProcessed);
                  int bs = Integer.parseInt(bloodSugar);
                  int tbs = Integer.parseInt(targetBloodSugar);
                  int p = Integer.parseInt(physical);
                  
                  if(cb<60 || cb>120){
                    jButtonPersonal.setEnabled(false);
                  }else  if(cp<10 || cp>15){
                    jButtonPersonal.setEnabled(false);
                  }else  if(bs>250 || bs<120){
                    jButtonPersonal.setEnabled(false);
                  }else  if(tbs>120 || tbs<80){
                    jButtonPersonal.setEnabled(false);
                  }else  if(p>10 || p<0){
                    jButtonPersonal.setEnabled(false);
                  }else jButtonPersonal.setEnabled(true);
              }
            }
        };
        
        addChangeListener(jTextCarbosInMealPersonal,personalValueListener);
        addChangeListener(jTextFieldCarbosProcessedPersonal,personalValueListener);
        addChangeListener(jTextBloodSugarPersonal,personalValueListener);
        addChangeListener(jTextTargetBloodSugarPersonal,personalValueListener);
        addChangeListener(jTextTodayPhysicalActivity,personalValueListener);
        addChangeListener(jTextPhysicalSamples,personalValueListener);
        addChangeListener(jTextDropSamples,personalValueListener);
        
        //Background
        ChangeListener backgroundValueListener = new ChangeListener() {
            public void stateChanged(ChangeEvent changeEvent) {
                            
              jButtonDetailsBackground.setEnabled(false);
              jButtonDetailsPersonal.setEnabled(false);
              jButtonDetailsStandard.setEnabled(false);
              
              //Detectar valores correctos
                String weight= jTextWeightBackground.getText();
                if(weight.isEmpty()){
                    jButtonBackground.setEnabled(false);
                }else if(isNumeric(weight)){
                    int w = Integer.parseInt(weight);
                    if(w<=130 && w>=40){
                        jButtonBackground.setEnabled(true);
                    }else{
                        jButtonBackground.setEnabled(false);
                    }
                }
            }
        };
        
        addChangeListener(jTextWeightBackground,backgroundValueListener);
        
        jButtonBackground.setEnabled(false);
        jButtonStandard.setEnabled(false);
        jButtonPersonal.setEnabled(false);
        jButtonDetailsBackground.setEnabled(false);
        jButtonDetailsStandard.setEnabled(false);
        jButtonDetailsPersonal.setEnabled(false);
    } 
    
    /**
 * Installs a listener to receive notification when the text of any
 * {@code JTextComponent} is changed. Internally, it installs a
 * {@link DocumentListener} on the text component's {@link Document},
 * and a {@link PropertyChangeListener} on the text component to detect
 * if the {@code Document} itself is replaced.
 * 
 * @param text any text component, such as a {@link JTextField}
 *        or {@link JTextArea}
 * @param changeListener a listener to receive {@link ChangeEvent}s
 *        when the text is changed; the source object for the events
 *        will be the text component
 * @throws NullPointerException if either parameter is null
 */
public static void addChangeListener(JTextComponent text, ChangeListener changeListener) {
    Objects.requireNonNull(text);
    Objects.requireNonNull(changeListener);
    DocumentListener dl = new DocumentListener() {
        private int lastChange = 0, lastNotifiedChange = 0;

        @Override
        public void insertUpdate(DocumentEvent e) {
            changedUpdate(e);
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            changedUpdate(e);
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            lastChange++;
            SwingUtilities.invokeLater(() -> {
                if (lastNotifiedChange != lastChange) {
                    lastNotifiedChange = lastChange;
                    changeListener.stateChanged(new ChangeEvent(text));
                }
            });
        }
    };
    text.addPropertyChangeListener("document", (PropertyChangeEvent e) -> {
        Document d1 = (Document)e.getOldValue();
        Document d2 = (Document)e.getNewValue();
        if (d1 != null) d1.removeDocumentListener(dl);
        if (d2 != null) d2.addDocumentListener(dl);
        dl.changedUpdate(null);
    });
    Document d = text.getDocument();
    if (d != null) d.addDocumentListener(dl);
}
    
    public boolean isNumeric(String s) {  
        return s.matches("^-?\\d+$");  
    } 
    
    private void jButtonPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPersonalActionPerformed
        
        int cb = Integer.parseInt(jTextCarbosInMealPersonal.getText());
        int cp = Integer.parseInt(jTextFieldCarbosProcessedPersonal.getText());
        int bs = Integer.parseInt(jTextBloodSugarPersonal.getText());
        int tbs = Integer.parseInt(jTextTargetBloodSugarPersonal.getText());
        int p = Integer.parseInt(jTextTodayPhysicalActivity.getText());
       
       int result = myvoter.personalInsulin(cb,cp,bs,tbs,p,physicalSamplesArray,dropSamplesArray);
       if(result == -1){
           jTextAreaResultPersonal.setText("Timeout");
       }else{
           jTextAreaResultPersonal.setText("Insulin doses you should take: "+result);
       }
       jButtonDetailsPersonal.setEnabled(true);
        
    }//GEN-LAST:event_jButtonPersonalActionPerformed

    private void jButtonStandardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStandardActionPerformed
        int cb = Integer.parseInt(jTextCarbosInMealStandard.getText());
        int cp = Integer.parseInt(jTextFieldCarbosProcessedStandard.getText());
        int bs = Integer.parseInt(jTextBloodSugarStandard.getText());
        int tbs = Integer.parseInt(jTextTargetBloodSugarStandard.getText());
        int s = Integer.parseInt(jTextIndividualSensitivityStandard.getText());
        
        int result = myvoter.standardInsulin(cb,cp,bs,tbs,s);
       if(result == -1){
           jTextAreaResultStandard.setText("Timeout");
       }else{
           jTextAreaResultStandard.setText("Insulin doses you should take: "+result);
       }
       jButtonDetailsStandard.setEnabled(true);
    }//GEN-LAST:event_jButtonStandardActionPerformed

    private void jButtonBackgroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackgroundActionPerformed
        int w = Integer.parseInt(jTextWeightBackground.getText());
        
        int result = myvoter.backgroundInsulin(w);

        if(result == -1){
           jTextAreaResultBackground.setText("Timeout");
       }else{
           jTextAreaResultBackground.setText("Insulin doses you should take: "+result);
       }
       jButtonDetailsBackground.setEnabled(true);
        
    }//GEN-LAST:event_jButtonBackgroundActionPerformed

    private void jButtonDetailsPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetailsPersonalActionPerformed
        // TODO add your handling code here:
        jTextAreaResultPersonal.setText(myvoter.getDetalhada());
        jButtonDetailsPersonal.setEnabled(false);
    }//GEN-LAST:event_jButtonDetailsPersonalActionPerformed

    private void jButtonDetailsBackgroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetailsBackgroundActionPerformed
        // TODO add your handling code here:
        jTextAreaResultBackground.setText(myvoter.getDetalhada());        
        jButtonDetailsBackground.setEnabled(false);
    }//GEN-LAST:event_jButtonDetailsBackgroundActionPerformed

    private void jButtonDetailsStandardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetailsStandardActionPerformed
        // TODO add your handling code here:
           jTextAreaResultStandard.setText(myvoter.getDetalhada());        
           jButtonDetailsStandard.setEnabled(false);
    }//GEN-LAST:event_jButtonDetailsStandardActionPerformed

	/**
	 * @param args the command line arguments
	 */
	
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
        //</editor-fold>
		
		
		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ClientFrame().setVisible(true);
			}
                    
		});
                
                
                
             
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackground;
    private javax.swing.JButton jButtonDetailsBackground;
    private javax.swing.JButton jButtonDetailsPersonal;
    private javax.swing.JButton jButtonDetailsStandard;
    private javax.swing.JButton jButtonPersonal;
    private javax.swing.JButton jButtonStandard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelPersonal;
    private javax.swing.JPanel jPanelStandard;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextArea jTextAreaResultBackground;
    private javax.swing.JTextArea jTextAreaResultPersonal;
    private javax.swing.JTextArea jTextAreaResultStandard;
    private javax.swing.JTextField jTextBloodSugarPersonal;
    private javax.swing.JTextField jTextBloodSugarStandard;
    private javax.swing.JTextField jTextCarbosInMealPersonal;
    private javax.swing.JTextField jTextCarbosInMealStandard;
    private javax.swing.JTextField jTextDropSamples;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextFieldCarbosProcessedPersonal;
    private javax.swing.JTextField jTextFieldCarbosProcessedStandard;
    private javax.swing.JTextField jTextIndividualSensitivityStandard;
    private javax.swing.JTextField jTextPhysicalSamples;
    private javax.swing.JTextField jTextTargetBloodSugarPersonal;
    private javax.swing.JTextField jTextTargetBloodSugarStandard;
    private javax.swing.JTextField jTextTodayPhysicalActivity;
    private javax.swing.JTextField jTextWeightBackground;
    // End of variables declaration//GEN-END:variables

}
